apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "6"
      restartPolicy: OnFailure
