apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  parallelism: 1
  template:
    metadata:
      name: simple-job
      labels:
        app: simple-app
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "60"
      restartPolicy: OnFailure
