apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-robot
  namespace: ondemand-job
rules:
  - apiGroups:
      - ''
    resources: 
      - 'pods'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups: 
      - 'batch'
      #- 'extensions'
    resources: 
      - 'jobs'
    verbs: 
      - 'create'
      - 'delete'
